verbose: false
instrumentation:
    root: .
    default-excludes: true
    excludes:
      ["coverage/**"]
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    include-all-sources: true
    include-pid: false
reporting:
    print: summary
    reports:
        - html
    watermarks:
        statements: [60, 90]
        lines: [60, 90]
        functions: [60, 90]
        branches: [60, 90]
check:
    global:
        statements: 90
        lines: 90
        branches: 90
        functions: 90
        excludes: []
